import Head from 'next/head';
import Blogs from '../Components/Blogs';
import Header from '../Components/Header';
import Navigation from '../Components/Navigation';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />  
      <Header />  
      <Blogs />  

    </div>
  )
}
